FROM redhat/ubi9:9.4-1214.1726694543
ENV REV=2
RUN yum -y upgrade
RUN yum --allowerasing -y install curl xz nc

COPY adapter /w/adapter
COPY prepMinio.sh minio-bin-20231120.txz /w/
RUN /w/prepMinio.sh

WORKDIR "/w"

RUN rm -rf /w/minio-bin-20231120.txz
RUN du -hs /w/
